#!/bin/bash
cd /home/ec2-user/nest-mongo-ec2-env
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
nvm install node
node -e "console.log('Running Node.js ' + process.version)"
npm install rimraf -g
npm install forever@4.0.0 -g

# -- temporary --
npm install
npm run build