#!/bin/bash
cd /home/ec2-user/nest-mongo-ec2-env
curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -
yum install -y nodejs-12.18.4-1nodesource
npm install rimraf -g
npm install forever@4.0.0 -g